version: "2"
services:
  fruits:
    build: ./fruits
    container_name: fruits
    volumes:
      - './fruits:/app'
      - './util:/app/util'
    ports:
      - "80:80"
    links:
      - mongo
    restart: on-failure
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"