version: "2"
services:
  api:
    build: ./fruits
    volumes:
      - ./fruits:/app
    ports:
      - "80:80"
    links:
      - mongo
    restart: on-failure
  mongo:
    image: mongo
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
